/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#f7fbff",
        surface: "#f7fbff",
        "surface-dim": "#bfdbfe",
        "surface-bright": "#fbfdff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8fbff",
        "surface-container": "#dbeafe",
        "surface-container-high": "#dbeafe",
        "surface-container-highest": "#bfdbfe",
        "surface-variant": "#bfdbfe",
        "on-background": "#14231d",
        "on-surface": "#14231d",
        "on-surface-variant": "#6f667f",
        "inverse-surface": "#14231d",
        "inverse-on-surface": "#ffffff",
        outline: "#64748b",
        "outline-variant": "#bfdbfe",
        primary: "#2563eb",
        "on-primary": "#ffffff",
        "primary-container": "#eff6ff",
        "on-primary-container": "#1d4ed8",
        secondary: "#bfdbfe",
        "secondary-container": "#eff6ff",
        tertiary: "#d577aa",
        "tertiary-container": "#fae3ef",
        ink: "#14231d",
      },
      fontFamily: {
        display: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      borderRadius: {
        soft: "1rem",
        card: "1.5rem",
        panel: "2rem",
        hero: "3rem",
      },
      boxShadow: {
        ambient: "0 4px 24px rgba(37, 99, 235, 0.04)",
        float: "0 24px 60px rgba(37, 99, 235, 0.1)",
        teal: "0 24px 48px rgba(37, 99, 235, 0.16)",
      },
      spacing: {
        "container-pad": "40px",
        gutter: "24px",
        "section-gap": "80px",
        "card-pad": "32px",
      },
    },
  },
  plugins: [],
};
